## Objective: Learning to solve basic Python problems

Prerequisites: Module 1 listed @ https://www.appliedaicourse.com/course/11/Applied-Machine-learning-course - SQL

Tackle few simple problems relvant to AI/ML
    - Break a problem into smaller sub-problems.
    - Connecting the dots from sub-problems to coding-concepts.
    - Code-walkthrough + Putting it all together.
    - More focus on common errors and mistakes + reading function reference + fixing bugs
    - Exercise-problems for practice.
    - Introduce new concepts as we need.
    - Good programmers may not benifit much from this session.
    

In [7]:
import numpy as np
A9 = np.random.rand(5,4) 
print(A9)

[[0.69684034 0.48382307 0.37390192 0.82951532]
 [0.08653761 0.60053073 0.88762526 0.78882685]
 [0.67872551 0.53842495 0.80447309 0.77788702]
 [0.48325684 0.67893136 0.85243398 0.60419627]
 [0.27105877 0.19158533 0.8639843  0.26781736]]


### Problem 1: Add two randomly generated NumPy matrices using loops 
    - Sub-problems
    - Subproblems ---> coding concepts
    - Code-walkthrough + Mistakes
    - Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

In [81]:
# create random matrix A1 of size 5X4.
### Google " numpy create random matrices " & Read through the top 4-5 links
### https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/

import numpy as np
shape = (3,3,3)
A1 = np.random.randint(1,10,size=shape) # read documentation to understand the params. Google "np.random.rand reference" ---> https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

##COMMON-ERROR: np.random.rand(4,5)
##COMMON_ERROR: 

print(A1) # always print to ensure that everyhitng works fine.

print(A1.shape)


[[[1 6 9]
  [8 2 2]
  [1 7 6]]

 [[3 9 4]
  [3 4 5]
  [3 1 7]]

 [[7 5 7]
  [6 5 2]
  [9 5 4]]]
(3, 3, 3)


In [34]:
print(A1.shape()); #COMMON-ERROR

TypeError: 'tuple' object is not callable

In [35]:
print(A1.type); # COMMON-ERROR

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [36]:
print(type(A1));

<class 'numpy.ndarray'>


In [ ]:
# Read through the attributes and methods in numpy.ndarray class
## Google "numpy.ndarray" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

## Pre-Google programmers: Read reference docs.

In [82]:
# Create random Matrix A2
A2 = np.random.randint(1,10,size=shape);

print(A2);

[[[9 3 8]
  [3 8 3]
  [7 8 6]]

 [[3 6 5]
  [8 8 4]
  [6 9 4]]

 [[8 2 6]
  [1 6 9]
  [5 2 7]]]


In [40]:
# Add element wise using loops A1+A2 = B

## Google "Accessing i,j th element in an ndarray" ---> https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html
print(A1[2,3]);


0.8512727559569503


In [42]:
print(A1(2,3)); #COMMON_ERROR

TypeError: 'numpy.ndarray' object is not callable

In [43]:
B= A1+A2; # using + operator on ndarrays
print(B); 

[[1.04674353 1.02376141 0.24734025 1.34003619]
 [0.65651352 0.96152547 1.01994027 1.24486056]
 [0.73244892 1.14405294 0.51287312 1.55648084]
 [1.06831282 1.24648853 0.63860095 0.85423459]
 [1.11677994 0.69869252 1.27288072 1.59904866]]


In [46]:
(r,c) = A1.shape;
print(r,c)

5 4


In [17]:
#B[i,j] = A1[i,j] + A2 [i,j] 

for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[0.75982445 0.64696807 0.77462353 0.46739042]
 [0.73482859 0.70127993 0.74347612 1.18680573]
 [0.6109933  1.54382401 0.26970674 1.73935976]
 [0.09937862 1.01007779 0.17542869 1.57642109]
 [0.9214432  1.50666589 1.08931517 1.38679745]]


In [18]:
# OPTIMIZATION: Pre-allocate matrix B
B = np.zeros(5,4); # COMMON-ERROR

TypeError: Cannot interpret '4' as a data type

In [47]:
#Google "np.zeros" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html
B = np.zeros((5,4))

for i in range(r): # same code as earlier
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[1.04674353 1.02376141 0.24734025 1.34003619]
 [0.65651352 0.96152547 1.01994027 1.24486056]
 [0.73244892 1.14405294 0.51287312 1.55648084]
 [1.06831282 1.24648853 0.63860095 0.85423459]
 [1.11677994 0.69869252 1.27288072 1.59904866]]


In [88]:
Q = np.zeros((3,3,3))
Q

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

#### Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]
****************************************************************************************************************
****************************************************************************************************************
****************************************************************************************************************




In [79]:
import numpy as np

shape = (3, 3, 3)

# Generate two random 3D matrices
matrix11 = np.random.randint(1, 10, size=shape)
matrix22 = np.random.randint(1, 10, size=shape)

# Initialize an empty matrix to store the result
result = np.zeros(shape, dtype=int)

# Iterate over each element to compute the sum
for p in range(shape[0]):
    for q in range(shape[1]):
        for r in range(shape[2]):
            result[p, q, r] = matrix11[p, q, r] + matrix22[p, q, r]

# Display the matrices and the result
print("Matrix 1:\n", matrix11)
print("Matrix 2:\n", matrix22)
print("Resulting Matrix:\n", result)


Matrix 1:
 [[[1 1 7]
  [6 1 1]
  [1 7 9]]

 [[2 5 5]
  [1 3 5]
  [5 2 7]]

 [[1 6 4]
  [3 7 1]
  [8 9 7]]]
Matrix 2:
 [[[6 4 5]
  [4 5 5]
  [9 7 6]]

 [[6 8 9]
  [3 5 9]
  [4 8 2]]

 [[3 3 8]
  [3 8 2]
  [7 9 7]]]
Resulting Matrix:
 [[[ 7  5 12]
  [10  6  6]
  [10 14 15]]

 [[ 8 13 14]
  [ 4  8 14]
  [ 9 10  9]]

 [[ 4  9 12]
  [ 6 15  3]
  [15 18 14]]]


In [89]:
for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            Q[i,j,k] = A1[i,j,k] + A2[i,j,k];
        
print(Q)

[[[10.  9. 17.]
  [11. 10.  5.]
  [ 8. 15. 12.]]

 [[ 6. 15.  9.]
  [11. 12.  9.]
  [ 9. 10. 11.]]

 [[15.  7. 13.]
  [ 7. 11. 11.]
  [14.  7. 11.]]]


### Problem 2: Find if a given 2D-point is inside (or) outside a circle 
    - Subproblems.
    - Subproblems --> coding concepts.
    - putting it all together.
    - Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 
   

In [90]:
## input circle (C) and point(P)

# input circle params
# Google " input multiple values python 3" ---> https://www.geeksforgeeks.org/input-multiple-values-user-one-line-python/
print("Enter Cx, Cy, r:");
(Cx, Cy, r) = raw_input().split();

print(Cx, Cy, r); # always cross check using print statements

Enter Cx, Cy, r:


NameError: name 'raw_input' is not defined

In [94]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

Cx, Cy, r = input("Enter Cx, Cy, r:").split();



Enter Cx, Cy, r:5 6 7


In [95]:
# Google " SyntaxError: invalid syntax input Python3 string" --> https://stackoverflow.com/questions/25174925/syntax-error-for-input
Cx, Cy, r = raw_input("Enter Cx, Cy, r:").split();


NameError: name 'raw_input' is not defined

In [96]:
print(Cx, Cy,r)

5 6 7


In [97]:
# Input Px, Py

Px, Py = input("Enter Px, Py:").split()
print(Px, Py);

Enter Px, Py:1 2
1 2


In [98]:
# Check if P lies in C.
d = ( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [99]:
# Get input values and convert them to integers
Cx, Cy, r = map(int, input("Enter Cx, Cy, r: ").split())
Px, Py = map(int, input("Enter Px, Py: ").split())

# Calculate distance squared (d) between (Cx, Cy) and (Px, Py)
d = ( (Cx - Px)**2 + (Cy - Py)**2 )
print(d)

# Check if d is less than the radius squared (r^2)
if d < r**2:
    print("P lies inside the circle C.")
else:
    print("P lies outside the circle C.")


Enter Cx, Cy, r: 2 3 4
Enter Px, Py: 4 5
8
P lies inside the circle C.


In [100]:
# Check if P lies in C.

## String to Float. Very important to note that split() returns Strings
Cx = float(Cx);
Cy = float(Cy);
r =float(r);
Px= float(Px);
Py = float(Py);

import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

2.8284271247461903
P in C


#### Exercise: Find if a point is inside or outside a rectangle.

HINT: How do you represent a rectangle?

********************************************
********************************************
********************************************

In [3]:
# Check if P lies in R

# Get rectangle coordinates and point coordinates
x1, y1, x2, y2 = map(int, input("Enter bottom-left (x1, y1) and top-right (x2, y2) coordinates of the rectangle: ").split())
Px, Py = map(int, input("Enter the coordinates of the point (Px, Py): ").split())

# Check if the point is inside the rectangle
if x1 <= Px <= x2 and y1 <= Py <= y2:
    print("The point is inside the rectangle.")
else:
    print("The point is outside the rectangle.")




Enter bottom-left (x1, y1) and top-right (x2, y2) coordinates of the rectangle: 3 6 10 2
Enter the coordinates of the point (Px, Py): 5 10
The point is outside the rectangle.


### Problem 3: NumPy ndarray manupualtion operations


In [11]:
# 1. Reshape matrices: Very COMMON-ERRORS in Assignments
A = np.random.rand(5,4);
print(A);


[[0.45230133 0.54212761 0.88310845 0.31394954]
 [0.6989329  0.1152326  0.36168108 0.2367592 ]
 [0.57848143 0.95299349 0.33081791 0.39925786]
 [0.37038842 0.70530606 0.5042743  0.21763684]
 [0.6460416  0.66719714 0.90292319 0.26362871]]


In [12]:
## reshape into a vector row-major-order
###https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html 
### Patiently read the documentation and try alternaive params
print( np.reshape(A, 20, 'C'))


[0.45230133 0.54212761 0.88310845 0.31394954 0.6989329  0.1152326
 0.36168108 0.2367592  0.57848143 0.95299349 0.33081791 0.39925786
 0.37038842 0.70530606 0.5042743  0.21763684 0.6460416  0.66719714
 0.90292319 0.26362871]


In [13]:
print( np.reshape(A, 20, 'F'))

[0.45230133 0.6989329  0.57848143 0.37038842 0.6460416  0.54212761
 0.1152326  0.95299349 0.70530606 0.66719714 0.88310845 0.36168108
 0.33081791 0.5042743  0.90292319 0.31394954 0.2367592  0.39925786
 0.21763684 0.26362871]


In [15]:
print( np.reshape(A, (2,10), 'C'))

[[0.45230133 0.54212761 0.88310845 0.31394954 0.6989329  0.1152326
  0.36168108 0.2367592  0.57848143 0.95299349]
 [0.33081791 0.39925786 0.37038842 0.70530606 0.5042743  0.21763684
  0.6460416  0.66719714 0.90292319 0.26362871]]


In [16]:
print( np.reshape(A, (10,-1), 'C'))

[[0.45230133 0.54212761]
 [0.88310845 0.31394954]
 [0.6989329  0.1152326 ]
 [0.36168108 0.2367592 ]
 [0.57848143 0.95299349]
 [0.33081791 0.39925786]
 [0.37038842 0.70530606]
 [0.5042743  0.21763684]
 [0.6460416  0.66719714]
 [0.90292319 0.26362871]]


In [17]:
print( np.reshape(A, (-1,4), 'C'))

[[0.45230133 0.54212761 0.88310845 0.31394954]
 [0.6989329  0.1152326  0.36168108 0.2367592 ]
 [0.57848143 0.95299349 0.33081791 0.39925786]
 [0.37038842 0.70530606 0.5042743  0.21763684]
 [0.6460416  0.66719714 0.90292319 0.26362871]]


In [18]:
print( np.reshape(A, (4,6), 'C'))

ValueError: cannot reshape array of size 20 into shape (4,6)

#### Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [19]:
#2. Stacking
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)


[[0.63899872 0.75131639 0.83497137 0.44005353]
 [0.98434686 0.63825443 0.4862364  0.03480561]
 [0.04564599 0.35296345 0.23807983 0.95948494]
 [0.33623565 0.21630336 0.56621484 0.67264996]
 [0.70545686 0.61539122 0.87001985 0.67926261]]
[[0.19871044 0.24173375]
 [0.38957076 0.30639631]
 [0.05944886 0.75018995]
 [0.59852368 0.7727876 ]
 [0.68200161 0.52988684]]


In [24]:
# C = [A B]
C = np.hstack(A, B);
print(C)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [25]:
C = np.hstack((A, B)); # read documentation carefully
print(C)

[[0.63899872 0.75131639 0.83497137 0.44005353 0.19871044 0.24173375]
 [0.98434686 0.63825443 0.4862364  0.03480561 0.38957076 0.30639631]
 [0.04564599 0.35296345 0.23807983 0.95948494 0.05944886 0.75018995]
 [0.33623565 0.21630336 0.56621484 0.67264996 0.59852368 0.7727876 ]
 [0.70545686 0.61539122 0.87001985 0.67926261 0.68200161 0.52988684]]


In [28]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.hstack((A, B));
print(C)

[[0.96753738 0.06087441 0.1299544  0.70192205]
 [0.14264276 0.09921158 0.72439453 0.27085195]
 [0.33986844 0.96591925 0.14883495 0.41992675]
 [0.15565825 0.1651044  0.41881552 0.23956913]
 [0.42126606 0.01459732 0.88578267 0.61079339]]
[[0.8561999  0.27504501 0.64990581 0.73161331]
 [0.80718015 0.15841408 0.77528797 0.03103841]
 [0.38429991 0.93873605 0.69498084 0.81139549]
 [0.74933363 0.26464231 0.36283609 0.62251913]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [31]:
A = np.random.rand(5,4);
print(A);
B= np.random.rand(4,4);
print(B)
C = np.vstack((A, B)); #Vertical stacking
print(C)



[[0.94731283 0.38100803 0.64284567 0.10234098]
 [0.03842157 0.25192872 0.46530752 0.1489175 ]
 [0.15105115 0.22051898 0.7258901  0.20090433]
 [0.76834511 0.07321236 0.30027109 0.60862415]
 [0.47228233 0.85729066 0.8390221  0.44747277]]
[[0.12971149 0.18797714 0.28724857 0.59868599]
 [0.06649134 0.47090094 0.15476452 0.95042819]
 [0.31665064 0.31161652 0.72636746 0.71098731]
 [0.35240355 0.78365662 0.29809861 0.78479828]]
[[0.94731283 0.38100803 0.64284567 0.10234098]
 [0.03842157 0.25192872 0.46530752 0.1489175 ]
 [0.15105115 0.22051898 0.7258901  0.20090433]
 [0.76834511 0.07321236 0.30027109 0.60862415]
 [0.47228233 0.85729066 0.8390221  0.44747277]
 [0.12971149 0.18797714 0.28724857 0.59868599]
 [0.06649134 0.47090094 0.15476452 0.95042819]
 [0.31665064 0.31161652 0.72636746 0.71098731]
 [0.35240355 0.78365662 0.29809861 0.78479828]]


In [36]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors) in images is a good way to think of this
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [37]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(4, 3, 3)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [ ]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(5,4,2);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 4, 2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B));
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


#### Exercise: Achieve the above tranaomfrs using numpy.concatenate [https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate]
***********
***********
***********
***********


### Problem-4: Find peaks/max in an list
- problem definition


In [ ]:

A = [1,3,4,5,7,6,4,5,10,1];
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [ ]:
# Peaks: 7,10
# Peak: A[i-1] <= A[i] >= A[i+1]

for i in range(1, A.size - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

AttributeError: 'list' object has no attribute 'size'

In [ ]:
print(len(A));

10


In [ ]:
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [ ]:
# There is a bug in the above solution. Find it...


In [ ]:
A = [11,3,4,5,7,6,4,5,10,15];

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7


In [ ]:
# what about 11 and 15?

# boundary case
if A[0] >= A[1]:
    print(A[0])
    
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

# boundary case
if A[len(A)-1] >= A[len(A)-2]:
    print(A[len(A)-1])


In [ ]:
# LESSON: Donot forget boundary cases

#Question: Time Complexity = ?

#### Exercise: 
1. Find peaks which are max values in a window of size 2 on both sides.
2. Use scipy.signal.find_peaks [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html]

Additioanl reading: More efficient algos @ http://courses.csail.mit.edu/6.006/spring11/lectures/lec02.pdf

### Problem 5: Permutations of a list
- Problem definition: lst = [1,2,3]

In [ ]:
# Using libraries
from itertools import permutations 
  
p = permutations([1, 2, 3]) # refer: https://docs.python.org/3/library/itertools.html#itertools.permutations

# what is an iterable in Python [https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Iterables.html]

# print the permutations
for i in list(p): 
    print i 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [ ]:
# No fun!
# Write your own code. Any suggestions?
# Break the problem into smaller sub-problems

In [ ]:
[1,2,3]
[1,3,2]
[2,1,3]
[2,3,1]
[3,1,2]
[3,2,1]

[3, 2, 1]

In [ ]:
# source: https://stackoverflow.com/questions/13109274/python-recursion-permutations

def permutation(s):
   if len(s) == 1:
     return [s]

   perm_list = [] # resulting list
   for a in s:
     remaining_elements = [x for x in s if x != a]
     z = permutation(remaining_elements) # permutations of sub-list

     for t in z:
       perm_list.append([a] + t)

   return perm_list

s = [1,2,3];
p = permutation(s);
print(p)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


#### Exercise: [Combinations] All possible ways to pick 3 elements out of 5 elements

- HINT: Use recursion.
- Google "combinations in Python"

### Practice, practice and practice..

- Optional  Assignments at AAIC: https://go.aws/2JrmV4A [Functions] , https://drive.google.com/file/d/1VB3wJSt_Mq0HLP9uaqgsZBR4BLMFnkmY/view [Pandas]

- Basic Python: https://www.geeksforgeeks.org/python-programming-examples/
- NumPy: https://www.w3resource.com/python-exercises/numpy/index.php
